stages:
  - deploy

deploy:
  stage: deploy

  script:
    - rm -rf /www/ajfite.com/projects/csc471-finalproject/*
    - cp ProjectSite/index.html /www/ajfite.com/projects/csc471-finalproject/

  tags:
    - fremont
